defaults:
  - _self_
  - model: lars
  - dataset: synthetic_regression

exp:
  run_func: 
    _target_: experiment.run_train
  seed: 42
  log_dir: # set during runtime to automatically created dir

  n: 100
  p: 10

wandb:
  project: lars