defaults:
  - _self_
  - model: ridge_gd
  - dataset: synthetic_regression

exp:
  run_func: 
    _target_: experiment.run_train_val
  seed: 42
  log_dir: # set during runtime to automatically created dir

  n: 100
  p: 10
  split: 0.7

  min_lambda: 1e-1
  max_lambda: 1e-7
  n_lambdas: ${exp.p}

wandb:
  project: lars